kind: pipeline
type: docker
name: bi-api-deploy

steps:
  - name: mv-src
    image: node:16.4.0
    volumes:
      - name: bi-api
        path: /root/bi-api
    commands:
      - cp -Rf /drone/src /root/bi-api

  - name: ssh-deploy
    image: registry-intl.cn-shenzhen.aliyuncs.com/sztest/sz:ssh
    settings:
      host:
        from_secret: host
      password:
        from_secret: password
      username: root
      port: 22
      script:
        - cd /docker/drone/bi-api
        - sudo cp -Rf /docker/drone/bi-api/src/* /data/prod/baoxuan-api-test
#        - cd /data/prod/baoxuan-api
#        - cnpm install
#        - ./start.sh -m prod

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.qq.com
      port: 465
      username: 1875483499@qq.com
      password:
        from_secret: qq_smtp_code
      from: 1875483499@qq.com
      recipients: 1875483499@qq.com,1599456917@qq.com
    when:
      status:
        - success
        - failure

volumes:
  - name: bi-api
    host:
      path: /docker/drone/bi-api

trigger:
  ref:
    - refs/tags/*


