const taoBaoSingleItemMap = {
    "batchId": "批次号",
    "productName": "产品名称",
    "linkId": "链接ID",
    "operationLeader": "运营负责人",
    "productLineLeader": "产品线负责人",
    "purchaseLeader": "采购负责人",
    "shopName": "店铺名称",
    "linkType": "链接属性",
    "date": "日期",
    "firstLevelItem": "一级类目",
    "payAmount": "支付金额",
    "shouTaoVisitors": "手淘搜索访客数",
    "shouTaoBuyers": "手淘搜索买家数",
    "shouTaoReallyConversionRate": "手淘真转率",
    "profitAmount": "利润额",
    "profitRate": "利润率",
    "visitors": "访客数",
    "paidBuyers": "支付买家数",
    "sumShoppingCart": "总购物车数",
    "shoppingCartClickAmount": "车点击量",
    "shoppingCartSumClick": "车总点击率",
    "shoppingCartConversion": "车转化",
    "shoppingCartSumAmount": "车总花费",
    "shoppingCatSumRoi": "车总投产比",
    "payConversionRate": "支付转化率",
    "reallyDealRate": "真实成交率",
    "deductionPoint": "扣点",
    "juBaiCost": "聚百花费",
    "clickFarmingAmount": "刷单金额",
    "clickFarmingCount": "刷单金笔数",
    "reallyPaidAmount": "实际支付金额",
    "refund": "退款",
    "reallyShipmentAmount": "实际发货金额",
    "cost": "成本",
    "freight": "运费",
    "shouTaoPeopleNumMarketRate": "手淘人数市场占比",
    "salesMarketRate": "坑产市场占比",
    "shouTaoPeopleNumMarketRateCircleRateDay": "手淘人数市场占比环比（日）",
    "salesMarketRateCircleRateDay": "坑市场占比环比（日）",
    "shouTaoPeopleNumMarketRateCircleRate7day": "手淘人数市场占比环比（7天）",
    "salesMarketRateCircleRate7day": "坑市场占比环比（7天）",
    "shouTaoPeopleNumMarketRateCircleRate30day": "手淘人数市场占比环比（30天）",
    "salesMarketRateCircleRate30day": "坑市场占比环比（30天）",
    "brandFirstBuySumAmount": "品牌新享费用合计",
    "xiaoHongShuRefund": "小红书返款"
}

module.exports = {
    taoBaoSingleItemMap
}