const flowUtil = require("@/utils/flowUtil")
const assert = require("assert")

describe("flowUtil", ()=>{
    describe("getLatestUniqueReviewItems", ()=>{
        it('', function () {
            const data = [
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "operateTimeGMT": "2024-04-19T11:28Z",
                    "showName": "视觉方案审核",
                    "operateType": "EXECUTE_TASK_NORMAL",
                    "remark": "同意",
                    "taskHoldTimeGMT": 0,
                    "type": "HISTORY",
                    "operatorName": "田辉",
                    "actionExit": "agree",
                    "operatorUserId": "013732072734966745",
                    "activityId": "node_oclii6vcap3",
                    "size": 1,
                    "dataId": 28911119586,
                    "domainList": [],
                    "operatorDisplayName": "田辉",
                    "action": "同意",
                    "taskId": "28909205997",
                    "operatorPhotoUrl": "//img.alicdn.com/tfs/TB1mKVJSpXXXXcwaXXXXXXXXXXX-78-80.jpg",
                    "cost": "0.40",
                    "requiredCost": 8,
                    "isOverDue": false
                },
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "operateTimeGMT": "2024-04-19T13:56Z",
                    "showName": "样品与道具确认",
                    "operateType": "EXECUTE_TASK_NORMAL",
                    "remark": "提交",
                    "taskHoldTimeGMT": 0,
                    "type": "HISTORY",
                    "operatorName": "李飞",
                    "actionExit": "agree",
                    "operatorUserId": "011964550359858960",
                    "activityId": "node_oclii6vcap5",
                    "size": 1,
                    "dataId": 28921850314,
                    "domainList": [],
                    "operatorDisplayName": "李飞",
                    "action": "提交",
                    "taskId": "28911119590",
                    "operatorPhotoUrl": "//img.alicdn.com/tfs/TB1mKVJSpXXXXcwaXXXXXXXXXXX-78-80.jpg",
                    "cost": "2.47",
                    "requiredCost": 16,
                    "isOverDue": false
                },
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "operateTimeGMT": "2024-04-22T15:38Z",
                    "showName": "确认样品与道具",
                    "operateType": "EXECUTE_TASK_NORMAL",
                    "remark": "同意",
                    "taskHoldTimeGMT": 0,
                    "type": "HISTORY",
                    "operatorName": "于浩",
                    "actionExit": "agree",
                    "operatorUserId": "2103600332651419",
                    "activityId": "node_oclii6vcap6",
                    "size": 1,
                    "dataId": 29108117746,
                    "domainList": [],
                    "operatorDisplayName": "于浩",
                    "action": "同意",
                    "taskId": "28921850318",
                    "operatorPhotoUrl": "https://static.dingtalk.com/media/lQLPM5VCVPnxZGHNAyDNAyCwgB-RXCxbdxAGAHxPSNk6AA_800_800.png",
                    "cost": "19.70",
                    "requiredCost": 4,
                    "isOverDue": true
                },
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "operateTimeGMT": "2024-04-24T12:49Z",
                    "showName": "摄影拍照",
                    "operateType": "REDIRECT_PROCESS",
                    "remark": "退回，缺少道具",
                    "taskHoldTimeGMT": 0,
                    "type": "HISTORY",
                    "operatorName": "高悦斌",
                    "actionExit": "restart",
                    "operatorUserId": "02421711126038887038",
                    "activityId": "node_oclii6vcap7",
                    "size": 1,
                    "dataId": 29244917921,
                    "domainList": [],
                    "operatorDisplayName": "高悦斌",
                    "action": "重定向流程实例",
                    "taskId": "null",
                    "operatorPhotoUrl": "https://static.dingtalk.com/media/lQDPD4LqDU_33xXNBM_NBMywtMCkCUJAKVYGDCXQYNKcAA_1228_1231.jpg",
                    "cost": "15.19",
                    "requiredCost": 24,
                    "isOverDue": false
                },
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "operateTimeGMT": "2024-04-29T17:23Z",
                    "showName": "样品与道具确认",
                    "operateType": "EXECUTE_TASK_NORMAL",
                    "remark": "提交",
                    "taskHoldTimeGMT": 0,
                    "type": "HISTORY",
                    "operatorName": "李飞",
                    "actionExit": "agree",
                    "operatorUserId": "011964550359858960",
                    "activityId": "node_oclii6vcap5",
                    "size": 1,
                    "dataId": 29593412634,
                    "domainList": [],
                    "operatorDisplayName": "李飞",
                    "action": "提交",
                    "taskId": "29244917919",
                    "operatorPhotoUrl": "//img.alicdn.com/tfs/TB1mKVJSpXXXXcwaXXXXXXXXXXX-78-80.jpg",
                    "cost": "77.91",
                    "requiredCost": 16,
                    "isOverDue": true
                },
                {
                    "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                    "showName": "确认样品与道具",
                    "taskHoldTimeGMT": 935426031,
                    "type": "TODO",
                    "operatorName": "于浩",
                    "actionExit": "doing",
                    "operatorUserId": "2103600332651419",
                    "activityId": "node_oclii6vcap6",
                    "taskType": "COMMON_ALL_AT_ONCE",
                    "size": 4,
                    "domainList": [
                        {
                            "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                            "showName": "确认样品与道具",
                            "taskHoldTimeGMT": 935426031,
                            "type": "TODO",
                            "operatorName": "于浩",
                            "operator": "2103600332651419",
                            "formatAction": "doing",
                            "activityId": "node_oclii6vcap6",
                            "taskType": "COMMON_ALL_AT_ONCE",
                            "size": 1,
                            "operatorDisplayName": "于浩",
                            "operatorAgentIdList": [],
                            "activeTimeGMT": "2024-04-29T17:23Z",
                            "taskId": "29593412638",
                            "operatorPhotoUrl": "https://static.dingtalk.com/media/lQLPM5VCVPnxZGHNAyDNAyCwgB-RXCxbdxAGAHxPSNk6AA_800_800.png",
                            "cost": "134.38",
                            "requiredCost": 4,
                            "isOverDue": true
                        },
                        {
                            "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                            "showName": "确认样品与道具",
                            "taskHoldTimeGMT": 935426031,
                            "type": "TODO",
                            "operatorName": "杨雪",
                            "operator": "1228451750859266",
                            "formatAction": "doing",
                            "activityId": "node_oclii6vcap6",
                            "taskType": "COMMON_ALL_AT_ONCE",
                            "size": 1,
                            "operatorDisplayName": "杨雪",
                            "operatorAgentIdList": [],
                            "activeTimeGMT": "2024-04-29T17:23Z",
                            "taskId": "29593412639",
                            "operatorPhotoUrl": "//img.alicdn.com/tfs/TB1mKVJSpXXXXcwaXXXXXXXXXXX-78-80.jpg",
                            "cost": "134.38",
                            "requiredCost": 4,
                            "isOverDue": true
                        },
                        {
                            "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                            "showName": "确认样品与道具",
                            "taskHoldTimeGMT": 935426031,
                            "type": "TODO",
                            "operatorName": "高悦斌",
                            "operator": "02421711126038887038",
                            "formatAction": "doing",
                            "activityId": "node_oclii6vcap6",
                            "taskType": "COMMON_ALL_AT_ONCE",
                            "size": 1,
                            "operatorDisplayName": "高悦斌",
                            "operatorAgentIdList": [],
                            "activeTimeGMT": "2024-04-29T17:23Z",
                            "taskId": "29593412640",
                            "operatorPhotoUrl": "https://static.dingtalk.com/media/lQDPD4LqDU_33xXNBM_NBMywtMCkCUJAKVYGDCXQYNKcAA_1228_1231.jpg",
                            "cost": "134.38",
                            "requiredCost": 4,
                            "isOverDue": true
                        },
                        {
                            "processInstanceId": "6b01bb71-2faa-4829-831a-dd1cf6367aa6",
                            "showName": "确认样品与道具",
                            "taskHoldTimeGMT": 935426031,
                            "type": "TODO",
                            "operatorName": "丁冬",
                            "operator": "1535601531639947",
                            "formatAction": "doing",
                            "activityId": "node_oclii6vcap6",
                            "taskType": "COMMON_ALL_AT_ONCE",
                            "size": 1,
                            "operatorDisplayName": "丁冬",
                            "operatorAgentIdList": [],
                            "activeTimeGMT": "2024-04-29T17:23Z",
                            "taskId": "29593412641",
                            "operatorPhotoUrl": "//img.alicdn.com/tfs/TB1mKVJSpXXXXcwaXXXXXXXXXXX-78-80.jpg",
                            "cost": "134.38",
                            "requiredCost": 4,
                            "isOverDue": true
                        }
                    ],
                    "operatorDisplayName": "于浩",
                    "activeTimeGMT": "2024-04-29T17:23Z",
                    "taskId": "29593412638",
                    "operatorPhotoUrl": "https://static.dingtalk.com/media/lQLPM5VCVPnxZGHNAyDNAyCwgB-RXCxbdxAGAHxPSNk6AA_800_800.png"
                },
                {
                    "showName": "摄影拍照",
                    "taskHoldTimeGMT": 0,
                    "type": "FORCAST",
                    "operatorName": "于浩",
                    "actionExit": "next",
                    "operatorUserId": "2103600332651419",
                    "activityId": "node_oclii6vcap7",
                    "taskType": "COMMON_ALL_AT_ONCE",
                    "size": 4
                }
            ]
            const newData = flowUtil.getLatestUniqueReviewItems(data)
            console.log(newData)
            const node1s = newData.filter(item=>item.activityId==="node_oclii6vcap7")
            assert.equal(node1s.length, 1)
            assert.equal(node1s[0].operateTimeGMT, null)
            const node2s = newData.filter(item=>item.activityId==="node_oclii6vcap6")
            assert.equal(node2s.length, 1)
            assert.equal(node2s[0].operateTimeGMT, null)
            const node3s = newData.filter(item=>item.activityId==="node_oclii6vcap5")
            assert.equal(node3s.length, 1)
            assert.equal(node3s[0].operateTimeGMT, "2024-04-29T17:23Z")
        })
    })
})